name: Playwright APITests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: write
jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    env: 
      TEST_ENV: qa

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      
    - name: Setup Node.js  
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Run API tests
      run: npx playwright test

    # - name: Upload Playwright Report
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 7

    - name: Generate Allure Report
      run: npm run allure:generate

    - name: Deploy Allure
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report