name: Playwright APITests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: write
jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    env: 
      TEST_ENV: qa

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup Node.js  
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Run API tests
      run: npx playwright test

    # - name: Upload Playwright Report
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 7

    # 前回のAllure履歴を取得
    - name: Checkout gh-pages
      if: always()
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
      continue-on-error: true

    # Historyを復元
    - name: Restore Allure History
      if: always()
      run: |
        mkdir -p allure-results

        if [ -d gh-pages/history ]; then
          cp -r gh-pages/history allure-results/
        fi

    # Allure Report生成
    - name: Generate Allure Report
      if: always()
      run: npm run allure:generate

    # GitHub Pagesへ公開
    - name: Deploy Allure Report
      if: always() && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        keep_files: true

    # Actions の Artifact からレポートをダウンロードできる
    # - name: Upload Allure Report Artifact
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: allure-report
    #     path: allure-report